base_url = "https://4ry1337.github.io"

title = "Rakhat Yskak"
description = ""

compile_sass = false
minify_html = true
author = "Rakhat Yskak"
generate_sitemap = true
generate_robots_txt = true
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
