base_url = "https://4ry1337.github.io"

title = "Rakhat Yskak"
description = ""
default_language = "en"

compile_sass = false
minify_html = true
author = "Rakhat Yskak"
generate_sitemap = true
generate_feeds = true
generate_robots_txt = true
taxonomies = [{ name = "tags" }]
build_search_index = true

[markdown]
render_emoji = true
lazy_async_image = true
bottom_footnotes = true
github_alerts = true

[markdown.highlighting]
light_theme = "github-light"                                                                                     
dark_theme = "github-dark"

[extra]
