name = "Rakhat Yskak"
title = "Software Engineer"
address.city = "Astana"
address.country = "Kazakhstan"
citizenship = "Kazakhstani"
summary = """
Motivated software engineer with hands-on experience in software development with 6+ months of industry experience and 4+ years in Computer Science and a background in Mathematics.
"""
