[[education]]
degree = "MS in Computer Science"
institution = "Nazarbayev University"
location = "Astana, Kazakhstan"
start_date = "2024-08-01"
end_date = "2026-05-31"
gpa = 3.67
gpa_scale = 4.0
status = "in_progress"
relevant_coursework = []
honors = []

[[education]]
degree = "BS in Software Engineering"
institution = "Astana IT University"
location = "Astana, Kazakhstan"
start_date = "2021-09-01"
end_date = "2024-06-30"
gpa = 3.56
gpa_scale = 4.0
status = "completed"
relevant_coursework = []
honors = []
