types = ["languages", "databases", "frameworks", "tools"]
levels = ["proficient", "familiar"]

[[technical.languages]]
name = "Rust"
level = "proficient"

[[technical.languages]]
name = "Javascrypt"
level = "proficient"

[[technical.languages]]
name = "C++"
level = "familiar"

[[technical.languages]]
name = "SQL"
level = "familiar"

[[technical.languages]]
name = "Typescript"
level = "familiar"

[[technical.tools]]
name = "Git"
level = "proficient"

[[technical.tools]]
name = "Docker"
level = "proficient"

[[technical.tools]]
name = "DigitalOcean"
level = "familiar"

[[technical.tools]]
name = "Github Actions"
level = "familiar"

[[technical.databases]]
name = "Postgresql"
level = "proficient"

[[technical.frameworks]]
name = "Actix-Web"
level = "proficient"

[[technical.frameworks]]
name = "Axum"
level = "proficient"

[[technical.frameworks]]
name = "Next.js"
level = "proficient"
