types = ["programming languages", "databases", "frameworks", "tools"]
levels = ["proficient", "familiar"]

[[skills]]
name = "rust"
type = "programming languages"
level = "proficient"

[[skills]]
name = "javascrypt"
type = "programming languages"
level = "proficient"

[[skills]]
name = "c++"
type = "programming languages"
level = "familiar"

[[skills]]
name = "sql"
type = "programming languages"
level = "familiar"

[[skills]]
name = "typescript"
type = "programming languages"
level = "familiar"

[[skills]]
name = "git"
type = "tools"
level = "proficient"

[[skills]]
name = "docker"
type = "tools"
level = "proficient"

[[skills]]
name = "postgresql"
type = "databases"
level = "proficient"

[[skills]]
name = "actix-web"
type = "frameworks"
level = "proficient"

[[skills]]
name = "axum"
type = "frameworks"
level = "proficient"

[[skills]]
name = "next.js"
type = "frameworks"
level = "proficient"
