[[contacts]]
name = "github"
url = "https://github.com/4ry1337"

[[contacts]]
name = "linkedin"
url = "https://www.linkedin.com/in/rakhat-yskak/"

[[contacts]]
name = "website"
url = "https://github.com/4ry1337"

[[contacts]]
name = "gmail"
url = "mailto:yskak.rakhat@gmail.com"
